#!/usr/bin/python

import os
import subprocess
import sys

command = sys.argv[1:]
command[0] = "/usr/libexec/openstack-tripleo/%s" % command[0]

os.environ["PATH"] = "%s:/usr/libexec/openstack-tripleo" % os.environ["PATH"]

sys.exit(subprocess.call(command))
